"""Configuration mapping all Level 10/20/30 curricula to their website IDs."""

CURRICULA = [
    # Arts Education
    {"name": "Arts Education 10, 20, 30", "id": 609, "category": "Arts Education"},
    {"name": "Band 10, 20, 30", "id": 610, "category": "Arts Education"},
    {"name": "Choral 10, 20, 30", "id": 607, "category": "Arts Education"},
    {"name": "Dance 10, 20, 30", "id": 484, "category": "Arts Education"},
    {"name": "Drama 10, 20, 30", "id": 485, "category": "Arts Education"},
    {"name": "Guitar 10, 20, 30", "id": 555, "category": "Arts Education"},
    {"name": "Instrumental Jazz 10", "id": 22, "category": "Arts Education"},
    {"name": "Instrumental Jazz 20", "id": 23, "category": "Arts Education"},
    {"name": "Instrumental Jazz 30", "id": 24, "category": "Arts Education"},
    {"name": "Music 10, 20, 30", "id": 487, "category": "Arts Education"},
    {"name": "Studio Art 20, 30", "id": 556, "category": "Arts Education"},
    {"name": "Visual Art 10, 20, 30", "id": 486, "category": "Arts Education"},
    {"name": "Vocal Jazz 10", "id": 449, "category": "Arts Education"},
    {"name": "Vocal Jazz 20", "id": 450, "category": "Arts Education"},
    {"name": "Vocal Jazz 30", "id": 451, "category": "Arts Education"},
    {"name": "Treaty Education Outcomes & Indicators (Arts)", "id": None, "category": "Arts Education", "treaty": True},
    # Languages
    {"name": "Core French 10, 20, 30", "id": 669, "category": "Languages"},
    {"name": "Dakota 10, 20, 30", "id": 788, "category": "Languages"},
    {"name": "Ukrainian 10, 20, 30", "id": 776, "category": "Languages"},
    {"name": "Core Ukrainian K-12", "id": 5, "category": "Languages"},
    {"name": "German 10, 20, 30", "id": 689, "category": "Languages"},
    {"name": "Mandarin 10, 20, 30", "id": 688, "category": "Languages"},
    {"name": "Spanish 10, 20, 30", "id": 687, "category": "Languages"},
    {"name": "Ukrainian-English Bilingual Education: Ukrainian Language Arts 9-12", "id": None, "category": "Languages", "skip": True},
    {"name": "Aboriginal Languages K-12", "id": 1, "category": "Languages"},
    {"name": "Dene 10, 20, 30", "id": 511, "category": "Languages"},
    {"name": "Michif 10, 20, 30", "id": 512, "category": "Languages"},
    {"name": "Michif French 10, 20, 30 (2026 PRELIMINARY)", "id": 806, "category": "Languages"},
    {"name": "Nakawē 10, 20, 30", "id": 513, "category": "Languages"},
    {"name": "Nakoda 10, 20, 30", "id": 661, "category": "Languages"},
    {"name": "nēhiyawēwin 10, 20, 30", "id": 2, "category": "Languages"},
    {"name": "American Sign Language and Deaf Culture 10, 20, 30", "id": 599, "category": "Languages"},
    {"name": "Treaty Education Outcomes & Indicators (Languages)", "id": None, "category": "Languages", "treaty": True},
    # English Language Arts
    {"name": "English Language Arts 10 (2025 PRELIMINARY)", "id": 791, "category": "English Language Arts"},
    {"name": "English Language Arts 10", "id": 37, "category": "English Language Arts"},
    {"name": "English Language Arts 20 (2025 PRELIMINARY)", "id": 792, "category": "English Language Arts"},
    {"name": "English Language Arts 20", "id": 38, "category": "English Language Arts"},
    {"name": "English Language Arts 30 (2025 PRELIMINARY)", "id": 793, "category": "English Language Arts"},
    {"name": "English Language Arts 30", "id": 39, "category": "English Language Arts"},
    {"name": "Creative Writing 20", "id": 673, "category": "English Language Arts"},
    {"name": "Journalism Studies 20", "id": 672, "category": "English Language Arts"},
    {"name": "Media Studies 20", "id": 693, "category": "English Language Arts"},
    {"name": "Treaty Education Outcomes & Indicators (ELA)", "id": None, "category": "English Language Arts", "treaty": True},
    # Financial Literacy
    {"name": "Financial Literacy 10 (2024 PRELIMINARY)", "id": 782, "category": "Financial Literacy 10"},
    {"name": "Financial Literacy 10 (2026 FINAL)", "id": 803, "category": "Financial Literacy 10"},
    # Physical Education & Wellness
    {"name": "Wellness 10", "id": 201, "category": "Physical Education & Wellness"},
    {"name": "Physical Education 20", "id": 453, "category": "Physical Education & Wellness"},
    {"name": "Physical Education 30", "id": 454, "category": "Physical Education & Wellness"},
    {"name": "Treaty Education Outcomes & Indicators (PE)", "id": None, "category": "Physical Education & Wellness", "treaty": True},
    # Sciences
    {"name": "Biology 30", "id": 68, "category": "Sciences"},
    {"name": "Chemistry 30", "id": 69, "category": "Sciences"},
    {"name": "Computer Science 20", "id": 446, "category": "Sciences"},
    {"name": "Computer Science 30", "id": 444, "category": "Sciences"},
    {"name": "Earth Science 30", "id": 76, "category": "Sciences"},
    {"name": "Environmental Science 20", "id": 73, "category": "Sciences"},
    {"name": "Health Science 20", "id": 74, "category": "Sciences"},
    {"name": "Physical Science 20", "id": 75, "category": "Sciences"},
    {"name": "Physics 30", "id": 72, "category": "Sciences"},
    {"name": "Science 10", "id": 63, "category": "Sciences"},
    {"name": "Treaty Education Outcomes & Indicators (Sciences)", "id": None, "category": "Sciences", "treaty": True},
    # Mathematics
    {"name": "Foundations of Mathematics and Pre-calculus 10", "id": 155, "category": "Mathematics"},
    {"name": "Foundations of Mathematics 20", "id": 156, "category": "Mathematics"},
    {"name": "Foundations of Mathematics 30", "id": 157, "category": "Mathematics"},
    {"name": "Pre-Calculus 20", "id": 158, "category": "Mathematics"},
    {"name": "Pre-Calculus 30", "id": 159, "category": "Mathematics"},
    {"name": "Workplace and Apprenticeship Mathematics 10", "id": 160, "category": "Mathematics"},
    {"name": "Workplace and Apprenticeship Mathematics 20", "id": 161, "category": "Mathematics"},
    {"name": "Workplace and Apprenticeship Mathematics 30", "id": 162, "category": "Mathematics"},
    {"name": "Calculus 30", "id": 163, "category": "Mathematics"},
    {"name": "Treaty Education Outcomes & Indicators (Math)", "id": None, "category": "Mathematics", "treaty": True},
    # Social Studies
    {"name": "Geography 10", "id": 188, "category": "Social Studies"},
    {"name": "History 10", "id": 186, "category": "Social Studies"},
    {"name": "Native Studies 10", "id": 179, "category": "Social Studies"},
    {"name": "Social Studies 10", "id": 173, "category": "Social Studies"},
    {"name": "Economics 20", "id": 183, "category": "Social Studies"},
    {"name": "Geography 20", "id": 189, "category": "Social Studies"},
    {"name": "History 20", "id": 185, "category": "Social Studies"},
    {"name": "Native Studies 20", "id": 180, "category": "Social Studies"},
    {"name": "Psychology 20", "id": 517, "category": "Social Studies"},
    {"name": "Social Studies 20", "id": 174, "category": "Social Studies"},
    {"name": "Economics 30", "id": 184, "category": "Social Studies"},
    {"name": "Geography 30", "id": 190, "category": "Social Studies"},
    {"name": "History 30: Canadian Studies", "id": 182, "category": "Social Studies"},
    {"name": "Law 30", "id": 514, "category": "Social Studies"},
    {"name": "Native Studies 30: Canadian Studies", "id": 181, "category": "Social Studies"},
    {"name": "Psychology 30", "id": 518, "category": "Social Studies"},
    {"name": "Social Studies 30: Canadian Studies", "id": 175, "category": "Social Studies"},
    {"name": "Treaty Education Outcomes & Indicators (Social Studies)", "id": None, "category": "Social Studies", "treaty": True},
    # Additional
    {"name": "Catholic Studies 9", "id": 412, "category": "Additional"},
    {"name": "Catholic Studies 10", "id": 413, "category": "Additional"},
    {"name": "Catholic Studies 20", "id": 414, "category": "Additional"},
    {"name": "Catholic Studies 30", "id": 415, "category": "Additional"},
    {"name": "Christian Ethics 10, 20, 30", "id": 775, "category": "Additional"},
    {"name": "Ukrainian-English Bilingual Education: Christian Ethics 9-12", "id": None, "category": "Additional", "skip": True},
    {"name": "Treaty Education Outcomes & Indicators (Additional)", "id": None, "category": "Additional", "treaty": True},
    # Practical & Applied Arts — Agriculture
    {"name": "Agribusiness 30", "id": 658, "category": "PAA: Agriculture", "modular": True},
    {"name": "Agricultural Equipment Technician 20, 30", "id": 660, "category": "PAA: Agriculture", "modular": True},
    {"name": "Agriculture Production A10, B10, A20, B20, A30, B30", "id": 691, "category": "PAA: Agriculture", "modular": True},
    {"name": "Agriculture and Sustainable Food Systems 20, 30", "id": 653, "category": "PAA: Agriculture", "modular": True},
    {"name": "Food Studies 10, 20, 30", "id": 668, "category": "PAA: Agriculture", "modular": True},
    # Practical & Applied Arts — Business and Management
    {"name": "Accounting 10, 20, 30", "id": 526, "category": "PAA: Business and Management", "modular": True},
    {"name": "Entrepreneurship 20, 30", "id": 659, "category": "PAA: Business and Management", "modular": True},
    {"name": "Marketing 20", "id": 560, "category": "PAA: Business and Management", "modular": True},
    # Practical & Applied Arts — Career and Life Management
    {"name": "Career and Work Exploration 10, 20, A30, B30", "id": 525, "category": "PAA: Career and Life Management", "modular": True},
    {"name": "Financial Literacy 20, 30", "id": 488, "category": "PAA: Career and Life Management", "modular": True},
    {"name": "Life Transitions 20, 30", "id": 569, "category": "PAA: Career and Life Management", "modular": True},
    # Practical & Applied Arts — Communication, Media and Design
    {"name": "Clothing, Textiles and Fashion 10, 20, 30", "id": 571, "category": "PAA: Communication, Media and Design", "modular": True},
    {"name": "Communication Media 10, 20, 30", "id": 113, "category": "PAA: Communication, Media and Design", "modular": True},
    {"name": "Design Studies 10, 20, 30", "id": 686, "category": "PAA: Communication, Media and Design", "modular": True},
    {"name": "Drafting and Computer-Aided Design 10, 20, 30", "id": 527, "category": "PAA: Communication, Media and Design", "modular": True},
    {"name": "Graphic Arts 20, 30", "id": 129, "category": "PAA: Communication, Media and Design", "modular": True},
    {"name": "Information Processing 10, 20, 30", "id": 535, "category": "PAA: Communication, Media and Design", "modular": True},
    {"name": "Interior Design and Decorating 30", "id": 568, "category": "PAA: Communication, Media and Design", "modular": True},
    {"name": "Photography 10, 20, 30", "id": 137, "category": "PAA: Communication, Media and Design", "modular": True},
    {"name": "Robotics and Automation 10, 20, 30", "id": 461, "category": "PAA: Communication, Media and Design", "modular": True},
    {"name": "Theatre Arts 20, 30", "id": 580, "category": "PAA: Communication, Media and Design", "modular": True},
    # Practical & Applied Arts — Construction, Manufacturing and Transportation
    {"name": "Autobody 10, A20, B20, A30, B30", "id": 538, "category": "PAA: Construction, Manufacturing and Transportation", "modular": True},
    {"name": "Construction and Carpentry 10, 20, 30", "id": 114, "category": "PAA: Construction, Manufacturing and Transportation", "modular": True},
    {"name": "Electrical and Electronics 10, Electrical 20, 30, Electronics 20, A30, B30", "id": 552, "category": "PAA: Construction, Manufacturing and Transportation", "modular": True},
    {"name": "Machining 10, 20, 30", "id": 741, "category": "PAA: Construction, Manufacturing and Transportation", "modular": True},
    {"name": "Mechanical and Automotive 10, A20, B20, A30, B30", "id": 543, "category": "PAA: Construction, Manufacturing and Transportation", "modular": True},
    {"name": "Welding 10, 20, A30, B30", "id": 143, "category": "PAA: Construction, Manufacturing and Transportation", "modular": True},
    # Practical & Applied Arts — Health Care, Hospitality and Human Services
    {"name": "Early Learning, Supportive Care 20, 30", "id": 732, "category": "PAA: Health Care, Hospitality and Human Services", "modular": True},
    {"name": "Commercial Cooking 10, 20, 30", "id": 524, "category": "PAA: Health Care, Hospitality and Human Services", "modular": True},
    {"name": "Emergency Services 20, 30", "id": 744, "category": "PAA: Health Care, Hospitality and Human Services", "modular": True},
    {"name": "Hairstyling and Esthetics 10, 20, 30", "id": 581, "category": "PAA: Health Care, Hospitality and Human Services", "modular": True},
    {"name": "Tourism 10, 20, 30", "id": 565, "category": "PAA: Health Care, Hospitality and Human Services", "modular": True},
    # Practical & Applied Arts — Resource Management
    {"name": "Energy and Mines 10, 20, 30", "id": 717, "category": "PAA: Resource Management", "modular": True},
    {"name": "Forestry Studies 20, 30", "id": 721, "category": "PAA: Resource Management", "modular": True},
    {"name": "Wildlife and Habitat Studies 10, 20, 30", "id": 723, "category": "PAA: Resource Management", "modular": True},
]

BASE_URL = "https://curriculum.gov.sk.ca"
