"""Configuration mapping all Level 10/20/30 curricula to their website IDs."""

CURRICULA = [
    # Arts Education
    {"name": "Arts Education 10, 20, 30", "id": 609, "category": "Arts Education"},
    {"name": "Band 10, 20, 30", "id": 610, "category": "Arts Education"},
    {"name": "Choral 10, 20, 30", "id": 607, "category": "Arts Education"},
    {"name": "Dance 10, 20, 30", "id": 484, "category": "Arts Education"},
    {"name": "Drama 10, 20, 30", "id": 485, "category": "Arts Education"},
    {"name": "Guitar 10, 20, 30", "id": 555, "category": "Arts Education"},
    {"name": "Instrumental Jazz 10", "id": 22, "category": "Arts Education"},
    {"name": "Instrumental Jazz 20", "id": 23, "category": "Arts Education"},
    {"name": "Instrumental Jazz 30", "id": 24, "category": "Arts Education"},
    {"name": "Music 10, 20, 30", "id": 487, "category": "Arts Education"},
    {"name": "Studio Art 20, 30", "id": 556, "category": "Arts Education"},
    {"name": "Visual Art 10, 20, 30", "id": 486, "category": "Arts Education"},
    {"name": "Vocal Jazz 10", "id": 449, "category": "Arts Education"},
    {"name": "Vocal Jazz 20", "id": 450, "category": "Arts Education"},
    {"name": "Vocal Jazz 30", "id": 451, "category": "Arts Education"},
    {"name": "Treaty Education Outcomes & Indicators (Arts)", "id": None, "category": "Arts Education", "treaty": True},
    # Languages
    {"name": "Core French 10, 20, 30", "id": 669, "category": "Languages"},
    {"name": "Dakota 10, 20, 30", "id": 788, "category": "Languages"},
    {"name": "Ukrainian 10, 20, 30", "id": 776, "category": "Languages"},
    {"name": "Core Ukrainian K-12", "id": 5, "category": "Languages"},
    {"name": "German 10, 20, 30", "id": 689, "category": "Languages"},
    {"name": "Mandarin 10, 20, 30", "id": 688, "category": "Languages"},
    {"name": "Spanish 10, 20, 30", "id": 687, "category": "Languages"},
    {"name": "Ukrainian-English Bilingual Education: Ukrainian Language Arts 9-12", "id": None, "category": "Languages", "skip": True},
    {"name": "Aboriginal Languages K-12", "id": 1, "category": "Languages"},
    {"name": "Dene 10, 20, 30", "id": 511, "category": "Languages"},
    {"name": "Michif 10, 20, 30", "id": 512, "category": "Languages"},
    {"name": "Michif French 10, 20, 30 (2026 PRELIMINARY)", "id": 806, "category": "Languages"},
    {"name": "Nakawē 10, 20, 30", "id": 513, "category": "Languages"},
    {"name": "Nakoda 10, 20, 30", "id": 661, "category": "Languages"},
    {"name": "nēhiyawēwin 10, 20, 30", "id": 2, "category": "Languages"},
    {"name": "American Sign Language and Deaf Culture 10, 20, 30", "id": 599, "category": "Languages"},
    {"name": "Treaty Education Outcomes & Indicators (Languages)", "id": None, "category": "Languages", "treaty": True},
    # English Language Arts
    {"name": "English Language Arts 10 (2025 PRELIMINARY)", "id": 791, "category": "English Language Arts"},
    {"name": "English Language Arts 10", "id": 37, "category": "English Language Arts"},
    {"name": "English Language Arts 20 (2025 PRELIMINARY)", "id": 792, "category": "English Language Arts"},
    {"name": "English Language Arts 20", "id": 38, "category": "English Language Arts"},
    {"name": "English Language Arts 30 (2025 PRELIMINARY)", "id": 793, "category": "English Language Arts"},
    {"name": "English Language Arts 30", "id": 39, "category": "English Language Arts"},
    {"name": "Creative Writing 20", "id": 673, "category": "English Language Arts"},
    {"name": "Journalism Studies 20", "id": 672, "category": "English Language Arts"},
    {"name": "Media Studies 20", "id": 693, "category": "English Language Arts"},
    {"name": "Treaty Education Outcomes & Indicators (ELA)", "id": None, "category": "English Language Arts", "treaty": True},
    # Financial Literacy
    {"name": "Financial Literacy 10 (2024 PRELIMINARY)", "id": 782, "category": "Financial Literacy 10"},
    {"name": "Financial Literacy 10 (2026 FINAL)", "id": 803, "category": "Financial Literacy 10"},
    # Physical Education & Wellness
    {"name": "Wellness 10", "id": 201, "category": "Physical Education & Wellness"},
    {"name": "Physical Education 20", "id": 453, "category": "Physical Education & Wellness"},
    {"name": "Physical Education 30", "id": 454, "category": "Physical Education & Wellness"},
    {"name": "Treaty Education Outcomes & Indicators (PE)", "id": None, "category": "Physical Education & Wellness", "treaty": True},
    # Sciences
    {"name": "Biology 30", "id": 68, "category": "Sciences"},
    {"name": "Chemistry 30", "id": 69, "category": "Sciences"},
    {"name": "Computer Science 20", "id": 446, "category": "Sciences"},
    {"name": "Computer Science 30", "id": 444, "category": "Sciences"},
    {"name": "Earth Science 30", "id": 76, "category": "Sciences"},
    {"name": "Environmental Science 20", "id": 73, "category": "Sciences"},
    {"name": "Health Science 20", "id": 74, "category": "Sciences"},
    {"name": "Physical Science 20", "id": 75, "category": "Sciences"},
    {"name": "Physics 30", "id": 72, "category": "Sciences"},
    {"name": "Science 10", "id": 63, "category": "Sciences"},
    {"name": "Treaty Education Outcomes & Indicators (Sciences)", "id": None, "category": "Sciences", "treaty": True},
    # Mathematics
    {"name": "Foundations of Mathematics and Pre-calculus 10", "id": 155, "category": "Mathematics"},
    {"name": "Foundations of Mathematics 20", "id": 156, "category": "Mathematics"},
    {"name": "Foundations of Mathematics 30", "id": 157, "category": "Mathematics"},
    {"name": "Pre-Calculus 20", "id": 158, "category": "Mathematics"},
    {"name": "Pre-Calculus 30", "id": 159, "category": "Mathematics"},
    {"name": "Workplace and Apprenticeship Mathematics 10", "id": 160, "category": "Mathematics"},
    {"name": "Workplace and Apprenticeship Mathematics 20", "id": 161, "category": "Mathematics"},
    {"name": "Workplace and Apprenticeship Mathematics 30", "id": 162, "category": "Mathematics"},
    {"name": "Calculus 30", "id": 163, "category": "Mathematics"},
    {"name": "Treaty Education Outcomes & Indicators (Math)", "id": None, "category": "Mathematics", "treaty": True},
    # Social Studies
    {"name": "Geography 10", "id": 188, "category": "Social Studies"},
    {"name": "History 10", "id": 186, "category": "Social Studies"},
    {"name": "Native Studies 10", "id": 179, "category": "Social Studies"},
    {"name": "Social Studies 10", "id": 173, "category": "Social Studies"},
    {"name": "Economics 20", "id": 183, "category": "Social Studies"},
    {"name": "Geography 20", "id": 189, "category": "Social Studies"},
    {"name": "History 20", "id": 185, "category": "Social Studies"},
    {"name": "Native Studies 20", "id": 180, "category": "Social Studies"},
    {"name": "Psychology 20", "id": 517, "category": "Social Studies"},
    {"name": "Social Studies 20", "id": 174, "category": "Social Studies"},
    {"name": "Economics 30", "id": 184, "category": "Social Studies"},
    {"name": "Geography 30", "id": 190, "category": "Social Studies"},
    {"name": "History 30: Canadian Studies", "id": 182, "category": "Social Studies"},
    {"name": "Law 30", "id": 514, "category": "Social Studies"},
    {"name": "Native Studies 30: Canadian Studies", "id": 181, "category": "Social Studies"},
    {"name": "Psychology 30", "id": 518, "category": "Social Studies"},
    {"name": "Social Studies 30: Canadian Studies", "id": 175, "category": "Social Studies"},
    {"name": "Treaty Education Outcomes & Indicators (Social Studies)", "id": None, "category": "Social Studies", "treaty": True},
    # Additional
    {"name": "Catholic Studies 9", "id": 412, "category": "Additional"},
    {"name": "Catholic Studies 10", "id": 413, "category": "Additional"},
    {"name": "Catholic Studies 20", "id": 414, "category": "Additional"},
    {"name": "Catholic Studies 30", "id": 415, "category": "Additional"},
    {"name": "Christian Ethics 10, 20, 30", "id": 775, "category": "Additional"},
    {"name": "Ukrainian-English Bilingual Education: Christian Ethics 9-12", "id": None, "category": "Additional", "skip": True},
    {"name": "Treaty Education Outcomes & Indicators (Additional)", "id": None, "category": "Additional", "treaty": True},
]

BASE_URL = "https://curriculum.gov.sk.ca"
